#  Copyright (C) 2023 GSI Helmholtzzentrum fuer Schwerionenforschung, Darmstadt
#  SPDX-License-Identifier: GPL-3.0-only
#  Authors: Sergei Zharko [committer] 
# 
## @file   config_ideal_hits_mcbm.yaml
## @brief  Configuration file for ideal hit producers
## @since  28.06.2023
## @author Sergei Zharko <s.zharko@gsi.de>

ideal_hit_producer:
  #
  # Flags are defined for each station
  # 0 - real hits
  # 1 - real hit position and time are adjusted with MC (exact quantity values are used)
  # 2 - real hit position and time are adjusted with MC (true values are smeared within corresponding error)
  # 3 - ideal hits are created (exact quantity values are used)
  # 4 - ideal hits are created (true values are smeared withing errors, defined in section parameters)
  flags:
    sts:
      0: 2
      1: 2
    trd:
      0: 2
      1: 2
      2: 2
    tof:
      0: 2
      1: 2
      2: 2
      3: 2
  #
  # Notes:
  # 1) For MVD, MuCh, TRD and TOF du corresponds to dx, and dv corresponds to dy
  # 2) Spatial errors are expressed in cm, time errors are expressed in ns 
  # 3) pdf stands for probability density function
  #
  # Available PDFs:
  #   g: bounded gaussian distribution
  #   u: uniform distribution
  parameters:
    sts:
      0: { du: { angle: 0, value: 10.e-4, pdf: g }, dv: { angle: 7.5, value: 10.e-4, pdf: g }, dt: { value: 2.9, pdf: g }}
      1: { du: { angle: 0, value: 10.e-4, pdf: g }, dv: { angle: 7.5, value: 10.e-4, pdf: g }, dt: { value: 2.9, pdf: g }}
    trd:
      0: { du: { angle: 0, value: .50, pdf: g }, dv: { angle: 90, value: .50, pdf: g }, dt: { value: 10., pdf: g }}
      1: { du: { angle: 0, value: .05, pdf: g }, dv: { angle: 90, value: 4.0, pdf: u }, dt: { value: 10., pdf: g }}
      2: { du: { angle: 0, value: 4.0, pdf: u }, dv: { angle: 90, value: .05, pdf: g }, dt: { value: 10., pdf: g }}
    tof:
      0: { du: { angle: 0, value: 0.45, pdf: g }, dv: { angle: 90, value: 0.25, pdf: g }, dt: { value: 0.075, pdf: g }}
      1: { du: { angle: 0, value: 0.45, pdf: g }, dv: { angle: 90, value: 0.25, pdf: g }, dt: { value: 0.075, pdf: g }}
      2: { du: { angle: 0, value: 0.45, pdf: g }, dv: { angle: 90, value: 0.25, pdf: g }, dt: { value: 0.075, pdf: g }}
      3: { du: { angle: 0, value: 0.45, pdf: g }, dv: { angle: 90, value: 0.25, pdf: g }, dt: { value: 0.075, pdf: g }}
