trigger:
  detector: STS
  window: 10
  threshold: 100
  deadtime: 50
eventbuilder:
  windows:
    STS: [-20, 30]
selector:
  minStationsSts: 0
  minStationsTof: 0
  minDigisBmon: 0
store:
  timeslice: false
  triggers: false
  events: true
qa:
  refreshrate: 100
