################################################
#                                              #
#  L1 Tracking Configuration File (prototype)  #
#                                              #
################################################

--- 
l1:
  setup: Null
  algorithm:
    # Parameters dependent on the CA track finder iteration
    # Iterations will be used in the same sequence as they defined below
    iterations:
      - name: "TESTFastPrimIter"
        min_n_hits:               4      
        min_n_hits_sta_0:         3
        track_chi2_cut:           10.
        triplet_chi2_cut:         23.4450
        doublet_chi2_cut:         7.56327
        pick_gather:              3.0
        pick_neighbour:           5.0
        max_qp:                   2. # (GeV/c)^-1,  1 / 0.5
        max_slope_pv:             1.1
        max_slope:                2.748
        max_dz:                   0. # cm
        min_start_triplet_lvl:    0
        first_station_index:      0
        target_pos_sigma_x:       1. # cm
        target_pos_sigma_y:       1. # cm
        is_primary:               true
        is_electron:              false
        max_station_gap:          0
        if_extend_tracks:         true
        if_suppress_ghost:        false
        is_track_from_triplets:   false
      - name: "AllPrimIter"
        min_n_hits:               4      
        min_n_hits_sta_0:         3
        track_chi2_cut:           10.
        triplet_chi2_cut:         23.4450
        doublet_chi2_cut:         7.56327
        pick_gather:              4.0
        pick_neighbour:           5.0
        max_qp:                   20. # (GeV/c)^-1,  1 / 0.05
        max_slope_pv:             1.1
        max_slope:                2.748
        max_dz:                   0.1 # cm
        min_start_triplet_lvl:    0
        first_station_index:      0
        target_pos_sigma_x:       1. # cm
        target_pos_sigma_y:       1. # cm
        is_primary:               true
        is_electron:              false
        max_station_gap:          0
        if_extend_tracks:         true
        if_suppress_ghost:        false
        is_track_from_triplets:   false
      - name: "AllPrimJumpIter"
        min_n_hits:               4      
        min_n_hits_sta_0:         4
        track_chi2_cut:           10.
        triplet_chi2_cut:         18.7560
        doublet_chi2_cut:         7.56327
        pick_gather:              4.0
        pick_neighbour:           5.0
        max_qp:                   10. # (GeV/c)^-1,  1 / 0.1
        max_slope_pv:             1.1
        max_slope:                2.748
        max_dz:                   0.1 # cm
        min_start_triplet_lvl:    0
        first_station_index:      0
        target_pos_sigma_x:       5. # cm
        target_pos_sigma_y:       5. # cm
        is_primary:               true
        is_electron:              false
        max_station_gap:          1
        if_extend_tracks:         true
        if_suppress_ghost:        true
        is_track_from_triplets:   false
      - name: "AllSecIter"
        min_n_hits:               4      
        min_n_hits_sta_0:         4
        track_chi2_cut:           10.
        triplet_chi2_cut:         18.7560
        doublet_chi2_cut:         7.56327
        pick_gather:              4.0
        pick_neighbour:           5.0
        max_qo:                   10. # (GeV/c)^-1,  1 / 0.1
        max_slope_pv:             1.5
        max_slope:                2.748
        max_dz:                   0.1 # cm
        min_start_triplet_lvl:    1
        first_station_index:      0
        target_pos_sigma_x:       10. # cm
        target_pos_sigma_y:       10. # cm
        is_primary:               false
        is_electron:              false
        max_station_gap:          0
        if_extend_tracks:         true    
        if_suppress_ghost:        true
        is_track_from_triplets:   false
...
