##################################################
#                                                #
#  File-object map for the QA-Checker framework  #
#                                                #
##################################################


checker:
  settings:
    ratio_min: 0.95
    ratio_max: 1.05
    pval_threshold: 0.05
  files:
    - name: "%v/%d_qa_ts_eb_ideal.qa.root"
      label: qa
      objects:
        - CbmCaInputQaSts/efficiencies/casts_reco_eff_vs_r_st0
        - CbmCaInputQaSts/efficiencies/casts_reco_eff_vs_xy_st0
        - CbmCaInputQaSts/histograms/casts_pull_t_st2
        - CbmCaInputQaSts/histograms/casts_res_x_vs_x_st2        
