#  Copyright (C) 2023 GSI Helmholtzzentrum fuer Schwerionenforschung, Darmstadt
#  SPDX-License-Identifier: GPL-3.0-only
#  Authors: Sergei Zharko [committer] 
# 
## @file   qa_task_config_mcbm.yaml
## @brief  Configuration file for QA-tasks in mCBM
## @since  27.07.2023
## @author Sergei Zharko <s.zharko@gsi.de>

qa:
  CbmCaInputQaMvd:
    check_list:
      station_position_ordering: true
      station_position_hit_delta_z: false
      hit_efficiency_station_%d: true
      pull_x_station_%d: true
      pull_y_station_%d: true
      pull_t_station_%d: true
      pull_station_%_pull_x: false
  CbmCaInputQaSts:
    check_list:
      station_position_ordering: true
      station_position_hit_delta_z: true
      hit_efficiency_station_%d: true
      pull_x_station_%d: true
      pull_y_station_%d: true
      pull_t_station_%d: true
      pull_u_%d_digis: false
      pull_v_%d_digis: false
  CbmCaInputQaTrd:
    check_list:
      station_position_ordering: true
      station_position_hit_delta_z: false
      hit_efficiency_station_%d: true
      hit_efficiency_station_0: false
      hit_efficiency_station_1: false
      pull_x_station_%d: true
      pull_y_station_%d: true
      pull_t_station_%d: false
  CbmCaInputQaTof:
    check_list:
      station_position_ordering: false
      station_position_hit_delta_z: false
      hit_efficiency_station_%d: true
      pull_x_station_%d: true
      pull_y_station_%d: true
      pull_t_station_%d: true

...
